language: node_js
node_js:
  - "lts/*"

install:
  - npm install

services: mongodb

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

scripts:
  - npm run build
  - npm run test
  - npm run test:cov

after_success:
  - npm run coveralls
